### ISSUE TITLE
File lost

### ISSUE THREAD

**Issue by LeiMazizizi** [wang-boyu/yelp-abm#1]
Hi! Thanks for sharing this interesting project. When I was running your code, it popped an error: 

"fiona.errors.DriverError: data/processed/ch_2_restaurants_st_louis_avg_sentiments.shp: No such file or directory"

I also looked through the directory and didn't get this .shp file.

Any ideas about it?

**Comment by wang-boyu** [comment]
Hi! Sorry about the problem - the data wasn't uploaded previously. It is now uploaded and a `git pull` should get it.

Let me know if it works.

**Comment by LeiMazizizi** [comment]
Thanks! Now it works! I'm about to close this issue.
